//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:\Documents\Repos\sungaila\Cdelta\src\Grammar\Language\CdeltaParser.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Cdelta.Language {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICdeltaParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public partial class CdeltaParserBaseListener : ICdeltaParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CdeltaParser.codeFile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCodeFile([NotNull] CdeltaParser.CodeFileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CdeltaParser.codeFile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCodeFile([NotNull] CdeltaParser.CodeFileContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CdeltaParser.namespace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespace([NotNull] CdeltaParser.NamespaceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CdeltaParser.namespace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespace([NotNull] CdeltaParser.NamespaceContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CdeltaParser.automatonDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAutomatonDefinition([NotNull] CdeltaParser.AutomatonDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CdeltaParser.automatonDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAutomatonDefinition([NotNull] CdeltaParser.AutomatonDefinitionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CdeltaParser.accessModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAccessModifier([NotNull] CdeltaParser.AccessModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CdeltaParser.accessModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAccessModifier([NotNull] CdeltaParser.AccessModifierContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CdeltaParser.automatonDataType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAutomatonDataType([NotNull] CdeltaParser.AutomatonDataTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CdeltaParser.automatonDataType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAutomatonDataType([NotNull] CdeltaParser.AutomatonDataTypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CdeltaParser.automatonBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAutomatonBody([NotNull] CdeltaParser.AutomatonBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CdeltaParser.automatonBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAutomatonBody([NotNull] CdeltaParser.AutomatonBodyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CdeltaParser.stateDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStateDefinition([NotNull] CdeltaParser.StateDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CdeltaParser.stateDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStateDefinition([NotNull] CdeltaParser.StateDefinitionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CdeltaParser.stateInnerBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStateInnerBlock([NotNull] CdeltaParser.StateInnerBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CdeltaParser.stateInnerBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStateInnerBlock([NotNull] CdeltaParser.StateInnerBlockContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CdeltaParser.stateEnter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStateEnter([NotNull] CdeltaParser.StateEnterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CdeltaParser.stateEnter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStateEnter([NotNull] CdeltaParser.StateEnterContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CdeltaParser.stateExit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStateExit([NotNull] CdeltaParser.StateExitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CdeltaParser.stateExit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStateExit([NotNull] CdeltaParser.StateExitContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CdeltaParser.transitionDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTransitionDefinition([NotNull] CdeltaParser.TransitionDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CdeltaParser.transitionDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTransitionDefinition([NotNull] CdeltaParser.TransitionDefinitionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CdeltaParser.transitionInnerBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTransitionInnerBlock([NotNull] CdeltaParser.TransitionInnerBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CdeltaParser.transitionInnerBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTransitionInnerBlock([NotNull] CdeltaParser.TransitionInnerBlockContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CdeltaParser.transitionEnter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTransitionEnter([NotNull] CdeltaParser.TransitionEnterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CdeltaParser.transitionEnter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTransitionEnter([NotNull] CdeltaParser.TransitionEnterContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace Cdelta.Language
